openapi: 3.0.0
info:
  title: Advanced To-Do App API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieves a list of all tasks.
      responses:
        '200':
          description: A list of tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Internal Server Error
    post:
      summary: Create a new task
      description: Creates a new task with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTask'
      responses:
        '201':
          description: Task created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input or duplicate title.
        '500':
          description: Internal Server Error
  /tasks/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
        description: ID of the task to retrieve, update, or delete.
    put:
      summary: Update an existing task
      description: Updates the details of a specific task.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: Task updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input.
        '404':
          description: Task not found.
        '500':
          description: Internal Server Error
    delete:
      summary: Delete a task
      description: Deletes a specific task by its ID.
      responses:
        '200':
          description: Task deleted successfully.
        '404':
          description: Task not found.
        '500':
          description: Internal Server Error

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task.
          readOnly: true
        title:
          type: string
          description: The description or name of the task.
          minLength: 1
          maxLength: 100
        completed:
          type: boolean
          description: Indicates if the task is completed.
          default: false
        priority:
          type: string
          description: The urgency level of the task.
          enum: [Low, Medium, High]
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the task was created.
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the task was last updated.
          readOnly: true
      required:
        - id
        - title
        - completed
        - priority
        - createdAt
        - updatedAt
    NewTask:
      type: object
      properties:
        title:
          type: string
          description: The description or name of the task.
          minLength: 1
          maxLength: 100
        priority:
          type: string
          description: The urgency level of the task.
          enum: [Low, Medium, High]
          default: Medium
      required:
        - title
    UpdateTask:
      type: object
      properties:
        title:
          type: string
          description: The description or name of the task.
          minLength: 1
          maxLength: 100
        completed:
          type: boolean
          description: Indicates if the task is completed.
        priority:
          type: string
          description: The urgency level of the task.
          enum: [Low, Medium, High]
      minProperties: 1
